name: IOS CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: macos-latest
    steps:
    - uses: browser-actions/setup-chrome@v1
    - uses: nanasess/setup-chromedriver@v2
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3.6.0
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'gradle'
    - name: Install the Appium and Driver
      run: |
        chmod +x ./scripts/RunAppiumServer.sh
        ./scripts/RunAppiumServer.sh
      shell: bash   
    - name: List iOS Devices & Platforms
      run: |
          xcrun simctl list
    - name: Install iOS 11.4 Runtime
      run: |
          gem install xcode-install
          xcversion simulators --install='iOS 14.2'
    - name: Create and Run iOS Emulator - iPhoneX on iOS 14.2, Update default appium config for iOS
      run: |
        xcrun simctl create TestiPhoneX com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-14-2 > deviceid.txt 
        DEVICEUUID=`cat deviceid.txt`          
        echo $DEVICEUUID        
        xcrun simctl boot $DEVICEUUID 

    - name: Run Test
      run: ./gradlew test --info
    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: unit_test_report
        path: /Users/runner/work/-appiumExample/  
        
